### ISSUE TITLE
Doubt with Our keypoints + Our bboox？

### ISSUE THREAD

**Issue by abeardear** [salihkaragoz/pose-residual-network-pytorch#1]
Hi@salihkaragoz Thank you for your novel work, i have some doubt when we do **real test**.

PRN is trained on both GT, when we test with our predicted keypoints and box, do we need to train it again, or just use the same model in this reposity? If we need to train it with Our keypoints + Our bboox, how can we prepare the input and target?

**Comment by salihkaragoz** [comment]
Hi @xiongzihua,
First of all sorry for the late reply. 

> PRN is trained on both GT, when we test with our predicted keypoints and box, do we need to train it again, or just use the same model in this repository? 

No, you don't need to train again, you can test with the same model.

We are planning to extend the Repo to get results for different keypoint and Bbox results.
I am closing this issue but do not hesitate to ask me for more info.
Thanks

**Comment by biras11** [comment]
Hi @salihkaragoz ! Is there a solution for these problems yet? Is it posible to test with our predicted keypoints and bboxes?
