### ISSUE TITLE
More details about the Fig.2 in your paper.

### ISSUE THREAD

**Issue by Ai-is-light** [salihkaragoz/pose-residual-network-pytorch#13]
@salihkaragoz Thanks for your excellent work and shared repo. I'm very interested in the Fig.2 results of your paper, and I would like to reproduce these results. And, would you mind sharing your code about how to get sample poses obtained via clustering the structures learned by PRN. 
Thanks.
Looking forward to your any replies

**Comment by mkocabas** [comment]
Hi @Ai-is-light, unfortunately we couldn't share the full pipeline in the paper due to some license issues.
