### ISSUE TITLE
Find some weird code in eval.py 

### ISSUE THREAD

**Issue by murdockhou** [salihkaragoz/pose-residual-network-pytorch#17]
Hi, thanks for your work. When I looking your code about this repository , i find somewhere is weird in eval.py. When to get predicated bbox_keypoints, you used the true keypoints to assign the bbox_keypoints. The code in eval.py is about line 200 and line 205. 

The peaks is true keypoints coordinate, is it right? It seems that used the true coordinate to assign the predicated bbox_keypoints. Actually i think the line 209~220 in eval.py is the right way to get real predicated bbox_keypoints. 

May be you can give me some advice about this, thanks.

**Comment by murdockhou** [comment]
is there anyone who can explain it for me?
thanks~

**Comment by jackyjsy** [comment]
Same issue here. It seems to me that the evaluation part uses the ground-truth keypoints to inference the estimated keypoints. @salihkaragoz  Could you explain our concerns in you evaluation code? Thanks!

**Comment by salihkaragoz** [comment]
Hi,
We are not using the PRN for keypoint prediction but to decide on which keypoints are associated with a bounding box. So the output of PRN is there for to score each keypoint not to finetune the input keypoints. Based on these scores we run a greedy assignment method to obtain final matchings.
Thanks
