### ISSUE TITLE
Hey @VladislavZavadskyy,

### ISSUE THREAD

**Issue by pavanteja295** [salihkaragoz/pose-residual-network-pytorch#18]
Could you clearly describe your problem instead of making a groundless judgment? This repo isn't a full pipeline of the things that we introduced in our recent paper, just a demo of the main contribution to help people to understand the idea. If you can state your issue in a concise way, maybe we can guide you to correct resources.

Thanks,

_Originally posted by @mkocabas in https://github.com/salihkaragoz/pose-residual-network-pytorch/issues/14#issuecomment-422727642_

Yes we would like you to direct us exactly the training methodology your preprocessing pipeline and ur hyper paramater tuning strategy. Or you could just release ur pretrained model which you were promising from long time.

**Comment by salihkaragoz** [comment]
Hi @pavanteja295, 

The download link of the pre-trained model is in the [README](https://github.com/salihkaragoz/pose-residual-network-pytorch/blob/master/README.md). Please refer to this issue https://github.com/mkocabas/pose-residual-network/issues/17.

Best
