### ISSUE TITLE
Pre-Trained model tar archive corrupted

### ISSUE THREAD

**Issue by nebojsaandjelkovic** [salihkaragoz/pose-residual-network-pytorch#24]
@salihkaragoz Provided pre trained model tar archive to reproduce test results is corrupted, 
https://drive.google.com/file/d/1OhdMllLGnpRAk6Wexw8LzXF_EHiolVj1/view?usp=sharing

Can you please provide a new one? 

Thank you in advance.

**Comment by immkapoor** [comment]
Did you get new one? The one I have downloaded is also corrupted

**Comment by AlexLacour** [comment]
Hello, how did you solve this issue ? @nebojsaandjelkovic
