### ISSUE TITLE
Corrupted tar archive

### ISSUE THREAD

**Issue by AlexLacour** [salihkaragoz/pose-residual-network-pytorch#27]
Hello,
Although the name of the issue is self-explanatory, I'll add a few details here :
- The archive is 806MB, that seems a bit large, especially when the pth file of a trained retina net is less than 200MB
- The file can't be opened, which is a shame, I'd love to replicate your results :)

I hope you will be able to help, have a nice day !

**Comment by salihkaragoz** [comment]
Hello there,

I checked the model link on the README page, it's working. Please check again. I'm adding a WGET link you can also try. 

Besides that, this repo doesn't include the Retinanet part of the paper. The pre-trained model is not related to Retinanet, it's about pose residual network which is responsible to match keypoints to the relevant persons in the image. Please read the paper in detail. 

`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1OhdMllLGnpRAk6Wexw8LzXF_EHiolVj1' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1OhdMllLGnpRAk6Wexw8LzXF_EHiolVj1" -O PRN.pth.tar && rm -rf /tmp/cookies.txt`

**Comment by AlexLacour** [comment]
Hello,
Thank you very much for your answer ! 
But even if the links are working (thank you for the wget link by the way), the archive can't be opened neither with tar on ubuntu18 or 7zip/winrar on windows10 (I have tried on 3 different computers).
As for the weight of the file : I know the repo only includes the prn module, but I don't understand why is the prn that heavy ? Is it because of the type of the weights (double maybe ?)

EDIT : I think I understand, it's supposed to be loaded directly using torch.load instead of unzipping it to get a pth file, sorry for the disturbance !
