### ISSUE TITLE
Downloadable weights

### ISSUE THREAD

**Issue by dmenig** [salihkaragoz/pose-residual-network-pytorch#3]
Hi. I'm very interested in this implementation. For now I'm gonna try training myself.

But do you think you'll put some downloadable weights that reach the scores thrown in the article ? I'd be very interested.

Thanks.

**Comment by salihkaragoz** [comment]
Hi @hyperfraise,
We have uploaded the best pre-trained model, you can download and try. The Repo works for only Coco Ground Truth. We can extend it for other types of results. 
I am closing that issue, let us know for further questions. 
Thanks
