### ISSUE TITLE
pretrain model is different from the defined model [Solved]

### ISSUE THREAD

**Issue by xjsxujingsong** [salihkaragoz/pose-residual-network-pytorch#9]
Hi, I download the code and pre-trained model. Then I just run test:
RuntimeError: Error(s) in loading state_dict for PRN:
	Missing key(s) in state_dict: "bneck.weight", "bneck.bias". 
	Unexpected key(s) in state_dict: "dens3.weight", "dens3.bias". 

It looks like the model definition is different from the pre-trainined model.

**Comment by salihkaragoz** [comment]
@xjsxujingsong Hello, 
We have updated the Repo. Can you clone the latest one? 
The model is compatible with the last version of Repo.
Feel free for further questions otherwise please close this issue.
Good Luck!

**Comment by xjsxujingsong** [comment]
I am using the latest code. i tried git clone and manually download the zip source code file. In the model.py file, I can see it has bneck, no dens3. It can be seen from the error as well: the pretrained model has no bneck, has dens3.  pls check it. Thanks.

**Comment by salihkaragoz** [comment]
Yes, you are completely right. We have trained the model with old layer names. After training, we have changed the names of layers in the Github Repo. Therefore there is a distinctness between pre-trained model and the Repo. I will change the names of layers in the pre-trained model.

But for a fast solution, you can change the two lines;
in the src/model.py
Line 22:
```
-  self.bneck     = nn.Linear(node_count, node_count)
+  self.dens3     = nn.Linear(node_count, node_count)
```

Line 31:
```
-  out = self.drop(F.relu(self.bneck(out)))
+  out = self.drop(F.relu(self.dens3(out)))
```
Thanks for your help.
